apiVersion: v1
kind: Template
labels:
  app: sonarqube
  template: sonarqube-imagestream
metadata:
  annotations:
    description: SonarQube - ImageStream
      see https://github.com/faust64/docker-sonarqube
    iconClass: icon-openshift
    openshift.io/display-name: SonarQube
    tags: sonarqube
  name: sonarqube-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Wsweet SonarQube image
    name: sonarqube-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  value: demo
